<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_VIEW_addToCompare</name>
   <tag></tag>
   <elementGuidId>b0561a4a-4bde-42d5-ab0e-2d6344d3d253</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BP000000316211</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BP000000316211']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bcd34c17-67d0-4f8e-be72-0e44d2375f61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>addtocompare__checkbox</value>
      <webElementGuid>e179bf60-cfaf-48dc-b4f4-76123970da01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a48af95c-5648-4979-9e3b-b94df6d27e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BP000000316211</value>
      <webElementGuid>b3402521-4f10-43ce-8977-1afaf86bbdb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addToCompare</value>
      <webElementGuid>6bbf6ab7-a30d-4678-8e3d-e8de914724c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BP000000316211&quot;)</value>
      <webElementGuid>9749d93d-47ac-4d59-8658-c3753e64e66f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BP000000316211']</value>
      <webElementGuid>725dbed6-a5e3-4ee8-adf6-9619df70f5cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section-bda7f20315']/heliux-addtocompare/div/div/input</value>
      <webElementGuid>dc2c5088-a052-4ec8-87f1-a25d8de9da90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>5a1cc874-b7e9-4fcd-a9e9-22cb8f16b938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'BP000000316211' and @name = 'addToCompare']</value>
      <webElementGuid>9fe98c75-ca83-479e-9adf-2e9183c173ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
