<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_VIEW_addToCompare_1_2</name>
   <tag></tag>
   <elementGuidId>0ef2ad2e-1d57-435e-b5fe-55dd7d9d7049</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BP000000164196</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BP000000164196']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bc08073f-0971-4acb-97dc-eb50a3563ec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>addtocompare__checkbox</value>
      <webElementGuid>e730778f-b310-473d-a70f-6af978f41f11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d879bad6-8c7b-4977-94ec-10183cc4bcdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BP000000164196</value>
      <webElementGuid>40752c5f-defc-48c5-aad1-963d8d3fd0e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addToCompare</value>
      <webElementGuid>f3dcd1f0-065a-4b93-b856-26b643740fc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BP000000164196&quot;)</value>
      <webElementGuid>70c7bff3-90f8-41ac-b747-73916a48e025</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BP000000164196']</value>
      <webElementGuid>72784464-f0be-4703-9386-4c3d731cc9d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section-f693f6eb84']/heliux-addtocompare/div/div/input</value>
      <webElementGuid>4750ff22-8894-409e-ad2a-07dfc3bed8bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div/heliux-section/div[3]/heliux-addtocompare/div/div/input</value>
      <webElementGuid>2d992bde-544a-4fe7-a1bd-e57b7477c6b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'BP000000164196' and @name = 'addToCompare']</value>
      <webElementGuid>642c5a72-6bd3-41e0-96b3-5676029f6e78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
