<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_VIEW_addToCompare_1</name>
   <tag></tag>
   <elementGuidId>95ad4663-eaca-4239-b605-fa96245ef75a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BP000000153476</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BP000000153476']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2aa6e324-aad2-43aa-a13b-7d0be673a3d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>addtocompare__checkbox</value>
      <webElementGuid>5d643192-aa39-48a4-869e-98fd4e2823b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8397ef9d-4931-4143-9468-078e0bc6ba4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BP000000153476</value>
      <webElementGuid>5e9dcf26-5cb5-47e7-9c50-22f911ad1b4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addToCompare</value>
      <webElementGuid>1be7e4a1-6e26-44dd-9a17-6f3e5fd867f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BP000000153476&quot;)</value>
      <webElementGuid>7c2a2a43-f799-44a3-b232-a777c7386073</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BP000000153476']</value>
      <webElementGuid>e1ea4815-d588-4373-ab86-62620003b579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section-f6cdddb3b9']/heliux-addtocompare/div/div/input</value>
      <webElementGuid>99c96625-9753-49e7-be70-78456dda9cd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/heliux-section/div[3]/heliux-addtocompare/div/div/input</value>
      <webElementGuid>1931bd95-e585-4583-b5e8-3b2392267455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'BP000000153476' and @name = 'addToCompare']</value>
      <webElementGuid>b5124c0d-4806-4ee6-912a-84285880ce10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
